### PR TITLE
Create GetStarted.md

### PR DESCRIPTION
**Pull request by berli0z**
installation guide

### CODE REVIEW

**Comment by berli0z** [comment]
Collections of screenshots to use 
chrome_1
chrome_3
firefox_1
firefox_2
chrome_2

**Comment by berli0z** [comment]
list of screenshots urls with red marks
[r_chrome_1](https://user-images.githubusercontent.com/40333748/52428452-43447680-2b02-11e9-89b9-4326334f0d9b.png)
[r_chrome_2](https://user-images.githubusercontent.com/40333748/52428454-43447680-2b02-11e9-8fc6-71784200a894.png)
[r_chrome_3](https://user-images.githubusercontent.com/40333748/52428456-43dd0d00-2b02-11e9-8adf-6c12120a4af7.png)
[r_firefox_1](https://user-images.githubusercontent.com/40333748/52428457-43dd0d00-2b02-11e9-9415-07b014f9482c.png)
[r_firefox_2](https://user-images.githubusercontent.com/40333748/52428458-4475a380-2b02-11e9-8151-9d6ac9d2bd2c.png)

**Comment by berli0z** [comment]
screenshots without red squares:
[chrome_00](https://user-images.githubusercontent.com/40333748/52487711-806e3e80-2bbe-11e9-8058-ac0a76361227.png)
[chrome_01](https://user-images.githubusercontent.com/40333748/52487712-8106d500-2bbe-11e9-8970-3687f18b469c.png)


[chrome_3](https://user-images.githubusercontent.com/40333748/52487757-9da30d00-2bbe-11e9-90dd-68bbbb5ac9b6.png)
[firefox_1](https://user-images.githubusercontent.com/40333748/52487759-9e3ba380-2bbe-11e9-8c96-c87dc35871ba.png)
[firefox_2](https://user-images.githubusercontent.com/40333748/52487760-9e3ba380-2bbe-11e9-85dc-5ad7a1303574.png)

[chrome_1](https://user-images.githubusercontent.com/40333748/52487754-9c71e000-2bbe-11e9-813e-7ad649388b6a.png)
[chrome_2](https://user-images.githubusercontent.com/40333748/52487756-9d0a7680-2bbe-11e9-8041-0603390b96e3.png)

**Comment by vecna** [comment]
@berli0z thanks, merged, and in the last commit you'll see how the page is configured.

**Pull request merged**
